version: '3.4'

services:
  db:
    image: mariadb:10.3
    environment:
      MYSQL_DATABASE: lw
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - ./db:/var/lib/mysql
      - ./mysql.conf.d:/etc/mysql/conf.d

  nginx:
    build:
      context: .
      target: static
    ports:
      - "80:80"

  app:
    build:
      context: .
      target: backend
    command: bash -c "pip install -r requirements.txt && python manage.py migrate && ./manage.py runserver 0.0.0.0:8080"
    volumes:
    - .:/code
    ports:
      - "8020:8080"
    depends_on:
      - db
    environment:
      DJANGO_ENV: dev
      DJANGO_SETTINGS_MODULE: 'lw.core.settings.dev'
      DB_NAME: 'lw'
      DB_USER: 'root'
      DB_PASSWORD: ''
      DB_HOST: db
      SECRET_KEY: secret_key
