version: '3.4'

services:
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432

  nginx:
    build:
      context: .
      target: static
    ports:
      - "80:80"

  app:
    build:
      context: .
      target: backend
    command: bash -c "pip install -r requirements.txt && python manage.py migrate && python -m pdb manage.py runserver 0.0.0.0:8080"
    volumes:
    - .:/code
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DJANGO_ENV: dev
      DJANGO_SETTINGS_MODULE: 'lw.core.settings.dev'
      DB_NAME: 'lw'
      DB_USER: 'postgres'
      DB_PASSWORD: ''
      DB_HOST: db
      DB_PORT: 5432
      SECRET_KEY: secret_key
