# Generated by Django 2.2.5 on 2019-09-07 12:41

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('translations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtail.core.fields.RichTextField(blank=True)),
                ('field_author', models.CharField(max_length=100)),
                ('field_translators', models.CharField(max_length=100)),
                ('field_original_link', models.CharField(max_length=100)),
                ('field_rfatz_id', models.PositiveSmallIntegerField()),
                ('field_on_vk', models.BooleanField()),
                ('field_readthesequences_link', models.CharField(max_length=100)),
                ('field_rating', models.PositiveSmallIntegerField()),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
