# Generated by Django 2.2.5 on 2019-09-07 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0003_bookpage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookpage',
            old_name='field_author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='bookpage',
            old_name='field_on_vk',
            new_name='on_vk',
        ),
        migrations.RenameField(
            model_name='bookpage',
            old_name='field_original_link',
            new_name='original_link',
        ),
        migrations.RenameField(
            model_name='bookpage',
            old_name='field_rating',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='bookpage',
            old_name='field_readthesequences_link',
            new_name='readthesequences_link',
        ),
        migrations.RenameField(
            model_name='bookpage',
            old_name='field_rfatz_id',
            new_name='rfatz_id',
        ),
        migrations.RenameField(
            model_name='bookpage',
            old_name='field_translators',
            new_name='translators',
        ),
        migrations.RenameField(
            model_name='translationpage',
            old_name='field_author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='translationpage',
            old_name='field_on_vk',
            new_name='on_vk',
        ),
        migrations.RenameField(
            model_name='translationpage',
            old_name='field_original_link',
            new_name='original_link',
        ),
        migrations.RenameField(
            model_name='translationpage',
            old_name='field_rating',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='translationpage',
            old_name='field_readthesequences_link',
            new_name='readthesequences_link',
        ),
        migrations.RenameField(
            model_name='translationpage',
            old_name='field_rfatz_id',
            new_name='rfatz_id',
        ),
        migrations.RenameField(
            model_name='translationpage',
            old_name='field_translators',
            new_name='translators',
        ),
    ]
