# Generated by Django 2.2.5 on 2019-09-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0004_no_field_prefix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookpage',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='translationpage',
            name='rating',
        ),
        migrations.AlterField(
            model_name='bookpage',
            name='author',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='bookpage',
            name='on_vk',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bookpage',
            name='original_link',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='bookpage',
            name='readthesequences_link',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='bookpage',
            name='rfatz_id',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookpage',
            name='translators',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='translationpage',
            name='author',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='translationpage',
            name='on_vk',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='translationpage',
            name='original_link',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='translationpage',
            name='readthesequences_link',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='translationpage',
            name='rfatz_id',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='translationpage',
            name='translators',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
