# Generated by Django 2.2.5 on 2019-11-02 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0006_translationpage_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookpage',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bookpage',
            name='original_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bookpage',
            name='readthesequences_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bookpage',
            name='translators',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
