# Generated by Django 2.2.5 on 2019-11-02 15:10

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0008_auto_20191102_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookpage',
            name='body',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
