# Generated by Django 2.2.5 on 2019-10-06 12:12

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='site_areas',
            field=wagtail.core.fields.StreamField([('site_area', wagtail.core.blocks.StructBlock([('header', wagtail.core.blocks.CharBlock(classname='title')), ('text', wagtail.core.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())]))], blank=True),
        ),
    ]
