# Generated by Django 2.2.5 on 2019-10-06 13:27

from django.db import migrations
import lw.core.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='site_areas',
            field=wagtail.core.fields.StreamField([('site_area', wagtail.core.blocks.StructBlock([('header', wagtail.core.blocks.CharBlock(classname='title')), ('text', wagtail.core.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('link', lw.core.blocks.URLOrAbsolutePathBlock())]))], blank=True),
        ),
    ]
