apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-django
spec:
  replicas: {{ .Values.django.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: {{ .Release.Name }}-django
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-django
    spec:
      initContainers:
        - name: migrations
          image: {{ .Values.django.image }}:{{ .Values.django.version }}
          ports:
            - containerPort: {{ .Values.django.port }}
          command: ["python", "manage.py", "migrate"]

          env:
            - name: DJANGO_SETTINGS_MODULE
              value: 'lw.core.settings.production'
            - name: DB_NAME
              value: {{ .Values.mariadb.db.name }}
            - name: DB_USER
              value: {{ .Values.mariadb.db.user }}
            - name: DB_HOST
              value: {{ .Release.Name }}-mariadb-headless
            - name: DB_PASSWORD
              value: {{ .Values.mariadb.db.password }}

      containers:
        - name: nginx
          image: {{ .Values.nginx.image }}:{{ .Values.nginx.version }}
          ports:
            - containerPort: {{ .Values.nginx.port }}

        - name: django
          image: {{ .Values.django.image }}:{{ .Values.django.version }}
          ports:
            - containerPort: {{ .Values.django.port }}

          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            failureThreshold: 3

          env:
            - name: DJANGO_SETTINGS_MODULE
              value: 'lw.core.settings.production'
            - name: DB_NAME
              value: {{ .Values.mariadb.db.name }}
            - name: DB_USER
              value: {{ .Values.mariadb.db.user }}
            - name: DB_HOST
              value: {{ .Release.Name }}-mariadb-headless
            - name: DB_PASSWORD
              value: {{ .Values.mariadb.db.password }}
            - name: SECRET_KEY
              value: secret_key

          resources:
            limits:
              memory: 200Mi
            requests:
              memory: 100Mi
