apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-django
  labels:
    app: {{ .Release.Name }}-django
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.django.port }}
    targetPort: {{ .Values.django.port }}
  selector:
    app: {{ .Release.Name }}-django
