apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nginx
  labels:
    app: {{ .Release.Name }}-nginx
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.nginx.servicePort }}
    targetPort: {{ .Values.nginx.port }}
  selector:
    app: {{ .Release.Name }}-nginx
